application: agreeablejunk
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: content/css
- url: /js
  static_dir: content/js 
  
- url: /new.*
  script: handlers.add.app
  login: required
  
- url: /search.*
  script: handlers.search.app
  login: required
  
- url: /
  script: handlers.list.app
  login: required
  
libraries:
- name: jinja2
  version: latest