application: helloworld
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /new.*
  script: Handlers.add.app
  
- url: /
  script: Handlers.list.app
  
libraries:
- name: jinja2
  version: latest